 
import "./globals.css";

 

export const metadata = {
  title: "Concept Learning Classes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body
        className={`font-puritan  antialiased py-3 px-3 h-screen w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
