
// app/layout.js
import "./globals.css";

import Asidebar from "@/components/navigation/Asidebar";
import { getLoggedInUser } from '@/lib/auth'; // This function uses mongoose
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
 
  import { ToastContainer } from 'react-toastify';
 
export const metadata = {
  title: "Concept Learning Classes",
  description: "Generated by Aryan",
};
// app/layout.js
export default async function RootLayout({ children }) {
   
 
  return (
    <html data-theme="light" lang="en">
      <body className="font-puritan antialiased min-h-screen w-screen  ">
     <ToastContainer /> 
      {children}
       
      </body>
    </html>
  );
}
