
// app/layout.js
import "./globals.css";

import Asidebar from "@/components/navigation/Asidebar";

export const metadata = {
  title: "Concept Learning Classes",
  description: "Generated by Aryan",
};
// app/layout.js
export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="font-puritan antialiased h-screen w-screen overflow-hidden">
        <main className="flex h-full w-full">
          <Asidebar /> {/* fixed or sticky sidebar */}
          <div className="flex-1 overflow-y-auto p-4">
            {children} {/* only this scrolls */}
          </div>
        </main>
      </body>
    </html>
  );
}
